version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "stylus-loader" # Ignore stylus-loader updates until vue-cli updates webpack
